/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Admin;

import Business.InsuranceSystem;

import java.awt.Container;

import view.UserListView;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import java.awt.Font;

/**
 *
 * @author xuhang
 */
public class AdminJPanel extends javax.swing.JPanel {

    private Container userProcessContainer;
    
    private InsuranceSystem system;
    /**
     * Creates new form AdminJPanel
     */
    public AdminJPanel(Container userProcessContainer, InsuranceSystem system) {
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	ImageIcon capitolIcon = new ImageIcon("./img/capitol-building.png");
    	ImageIcon customerIcon = new ImageIcon("./img/customer.png");
    	ImageIcon eyeIcon = new ImageIcon("./img/eye.png");
    	ImageIcon maninofficeIcon = new ImageIcon("./img/man-in-office-desk-with-computer.png");
    	ImageIcon managerIcon = new ImageIcon("./img/manager.png");
    	ImageIcon solutionIcon = new ImageIcon("./img/solution.png");

        gov = new javax.swing.JButton(capitolIcon);
        gov.setFont(new Font("Arial", Font.BOLD, 16));
        cus = new javax.swing.JButton(customerIcon);
        cus.setFont(new Font("Arial", Font.BOLD, 16));
        planner = new javax.swing.JButton(solutionIcon);
        planner.setFont(new Font("Arial", Font.BOLD, 16));
        dep = new javax.swing.JButton(managerIcon);
        dep.setFont(new Font("Arial", Font.BOLD, 16));
        viewAll = new javax.swing.JButton(eyeIcon);
        viewAll.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel1 = new javax.swing.JLabel(maninofficeIcon);

        gov.setText("Create Goverment User");
        gov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                govActionPerformed(evt);
            }
        });

        cus.setText("Create Customer");
        cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusActionPerformed(evt);
            }
        });

        planner.setText("Create Company Planner");
        planner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plannerActionPerformed(evt);
            }
        });

        dep.setText("Create Company Department");
        dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depActionPerformed(evt);
            }
        });

        viewAll.setText("All Created Users");
        viewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllActionPerformed(evt);
            }
        });

        jLabel1.setFont(new Font("Arial", Font.BOLD, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 1, 255));
        jLabel1.setText("Admin User Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(79)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(viewAll, GroupLayout.PREFERRED_SIZE, 242, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(planner, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(gov, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(cus, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(dep, GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)))
        				.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 235, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(53)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        			.addGap(35)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(gov, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
        				.addComponent(cus, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(planner, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        				.addComponent(dep, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(viewAll, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(217, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void govActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_govActionPerformed
        // TODO add your handling code here:
        userProcessContainer.removeAll();
        userProcessContainer.add(new CreateUserJPanel(userProcessContainer, system, "gov"));
        userProcessContainer.revalidate();
    }//GEN-LAST:event_govActionPerformed

    private void cusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusActionPerformed
        // TODO add your handling code here:
        userProcessContainer.removeAll();
        userProcessContainer.add(new CreateUserJPanel(userProcessContainer, system, "customer"));
        userProcessContainer.revalidate();
    }//GEN-LAST:event_cusActionPerformed

    private void plannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plannerActionPerformed
        // TODO add your handling code here:
        userProcessContainer.removeAll();
        userProcessContainer.add(new CreateUserJPanel(userProcessContainer, system, "planner"));
        userProcessContainer.revalidate();
    }//GEN-LAST:event_plannerActionPerformed

    private void depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depActionPerformed
        // TODO add your handling code here:
        userProcessContainer.removeAll();
        userProcessContainer.add(new CreateUserJPanel(userProcessContainer, system, "department"));
        userProcessContainer.revalidate();
    }//GEN-LAST:event_depActionPerformed

    private void viewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllActionPerformed
        // TODO add your handling code here:
        UserListView userListView = new UserListView(system);
    }//GEN-LAST:event_viewAllActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cus;
    private javax.swing.JButton dep;
    private javax.swing.JButton gov;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton planner;
    private javax.swing.JButton viewAll;
    // End of variables declaration//GEN-END:variables
}
