/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Customer;

import Business.InsuranceSystem;
import Business.Plan.Plan;
import CustomerApply.folder.CustomerPlan;
import java.awt.Container;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;

import java.awt.Font;
import java.awt.Color;

/**
 *
 * @author xuhang
 */
public class CustomerRequestJPanel extends javax.swing.JPanel {

    private InsuranceSystem system;
    
    private Container container;
    /**
     * Creates new form CustomerRequestJPanel
     */
    public CustomerRequestJPanel(Container container, InsuranceSystem system) {
        this.container = container;
        this.system = system;
        initComponents();
        initTable(system.getCustomerPlanDirectory().getCustomerPlans());

    }

    private void initTable(ArrayList<CustomerPlan> customerPlans) {
        DefaultTableModel model = (DefaultTableModel) planListTable.getModel();
        model.setRowCount(0);

        for (CustomerPlan customerPlan : customerPlans) {
            if (!customerPlan.getCustomer().equals(system.getCurrentUser())) {
                continue;
            }
            
            Plan plan = customerPlan.getPlan();
            Object[] row = new Object[7];
            row[0] = plan.getTitle();
            row[1] = plan.getPlanId();
            row[2] = plan.getPrice();
            row[3] = plan.getOfferField();
            row[4] = plan.getOfferAgeRange();
            row[5] = plan.getCovertimerange();
            row[6] = customerPlan.getStatus();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        planListTable = new javax.swing.JTable();
        planListTable.setFont(new Font("Arial", Font.BOLD, 14));
        ImageIcon showIcon = new ImageIcon("./img/customer.png");
        jLabel1 = new javax.swing.JLabel(showIcon);
        jLabel1.setForeground(Color.BLUE);
        jLabel1.setFont(new Font("Arial", Font.BOLD, 18));
        backJButton = new javax.swing.JButton();
        backJButton.setFont(new Font("Arial", Font.BOLD, 14));

        planListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title", "Plan id", "Price", "Offer Field", "Offer Age Range", "Cover Time Range", "Status"
            }
        ));
        jScrollPane1.setViewportView(planListTable);

        jLabel1.setText("Applied Plan Status");

        backJButton.setText("back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(36)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel1)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 726, GroupLayout.PREFERRED_SIZE)
        				.addComponent(backJButton))
        			.addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(51)
        			.addComponent(jLabel1)
        			.addGap(18)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 300, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(backJButton)
        			.addContainerGap(157, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        container.add(new CustomerMainJPanel(container, system));
        container.revalidate();
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable planListTable;
    // End of variables declaration//GEN-END:variables
}
